name: aquacropgrid_dev
channels:
  - conda-forge
  - defaults
dependencies:
  - affine=2.3.0
  - attrs=24.3.0
  - blas=1.0
  - blosc=1.21.3
  - boost-cpp=1.82.0
  - bottleneck=1.4.2
  - branca=0.6.0
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2025.2.25
  - cairo=1.16.0
  - cdsapi=0.7.6
  - certifi=2025.4.26
  - cfitsio=3.470
  - cftime=1.6.4
  - charset-normalizer=3.3.2
  - click=8.1.8
  - click-plugins=1.1.1
  - cligj=0.7.2
  - contourpy=1.3.1
  - cycler=0.11.0
  - cyrus-sasl=2.1.28
  - ecmwf-datastores-client=0.1.0
  - expat=2.7.1
  - folium=0.14.0
  - fontconfig=2.14.1
  - fonttools=4.55.3
  - freetype=2.13.3
  - freexl=2.0.0
  - geopandas=1.0.1
  - geopandas-base=1.0.1
  - geos=3.10.6
  - geotiff=1.7.0
  - gettext=0.21.0
  - giflib=5.2.2
  - hdf4=4.2.13
  - hdf5=1.14.5
  - icu=73.1
  - idna=3.7
  - jinja2=3.1.6
  - joblib=1.4.2
  - jpeg=9e
  - json-c=0.16
  - kealib=1.5.0
  - kiwisolver=1.4.8
  - krb5=1.20.1
  - lcms2=2.16
  - lerc=4.0.0
  - libboost=1.82.0
  - libcurl=8.12.1
  - libcxx=14.0.6
  - libdeflate=1.22
  - libedit=3.1.20230828
  - libev=4.33
  - libffi=3.4.4
  - libgdal=3.6.2
  - libgfortran=5.0.0
  - libgfortran5=11.3.0
  - libglib=2.78.4
  - libiconv=1.16
  - libkml=1.3.0
  - libnetcdf=4.8.1
  - libnghttp2=1.57.0
  - libopenblas=0.3.29
  - libpng=1.6.39
  - libpq=17.4
  - libspatialite=5.1.0
  - libssh2=1.11.1
  - libtiff=4.7.0
  - libwebp-base=1.3.2
  - libxml2=2.13.8
  - libzip=1.8.0
  - llvm-openmp=14.0.6
  - lz4-c=1.9.4
  - mapclassify=2.5.0
  - markupsafe=3.0.2
  - matplotlib-base=3.10.0
  - minizip=4.0.3
  - multiurl=0.3.5
  - ncurses=6.4
  - netcdf4=1.7.2
  - networkx=3.4.2
  - nspr=4.35
  - nss=3.89.1
  - numexpr=2.10.1
  - numpy=1.26.4
  - numpy-base=1.26.4
  - openjpeg=2.5.2
  - openldap=2.6.4
  - openssl=3.0.16
  - packaging=24.2
  - pandas=2.2.3
  - pcre2=10.42
  - pillow=11.1.0
  - pip=25.1
  - pixman=0.40.0
  - poppler=24.09.0
  - poppler-data=0.4.11
  - proj=9.3.1
  - pyogrio=0.10.0
  - pyparsing=3.2.0
  - pyproj=3.6.1
  - pysocks=1.7.1
  - python=3.10.16
  - python-dateutil=2.9.0post0
  - python-tzdata=2025.2
  - pytz=2024.1
  - qhull=2020.2
  - rasterio=1.4.3
  - readline=8.2
  - requests=2.32.3
  - rioxarray=0.19.0
  - scikit-learn=1.6.1
  - scipy=1.15.3
  - setuptools=78.1.1
  - shapely=2.0.6
  - six=1.17.0
  - sqlite=3.45.3
  - threadpoolctl=3.5.0
  - tiledb=2.3.3
  - tk=8.6.14
  - tqdm=4.67.1
  - typing_extensions=4.12.2
  - tzdata=2025b
  - unicodedata2=15.1.0
  - uriparser=0.9.7
  - urllib3=2.3.0
  - wheel=0.45.1
  - xarray=2024.11.0
  - xerces-c=3.2.4
  - xyzservices=2022.9.0
  - xz=5.6.4
  - zlib=1.2.13
  - zstd=1.5.6
